// 构建脚本：读取 posts/*.md，解析 frontmatter，生成 assets/js/posts-data.js
// 用法: node build.js
const fs = require("fs");
const path = require("path");

const POSTS_DIR = path.join(__dirname, "posts");
const OUT_FILE = path.join(__dirname, "assets", "js", "posts-data.js");

function parseFrontmatter(raw) {
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
  if (!match) return { meta: {}, content: raw };
  const meta = {};
  match[1].split(/\r?\n/).forEach((line) => {
    const m = line.match(/^(\w+):\s*(.*)$/);
    if (!m) return;
    let value = m[2].trim();
    if (value.startsWith("[") && value.endsWith("]")) {
      value = value
        .slice(1, -1)
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean);
    }
    meta[m[1]] = value;
  });
  return { meta, content: match[2] };
}

const posts = fs
  .readdirSync(POSTS_DIR)
  .filter((f) => f.endsWith(".md"))
  .map((file) => {
    const raw = fs.readFileSync(path.join(POSTS_DIR, file), "utf8");
    const { meta, content } = parseFrontmatter(raw);
    return {
      id: meta.id || file.replace(/\.md$/, ""),
      title: meta.title || "未命名",
      date: meta.date || "1970-01-01",
      tags: Array.isArray(meta.tags) ? meta.tags : [],
      summary: meta.summary || "",
      type: meta.type || "post",
      content: content.trim(),
    };
  })
  .sort((a, b) => (a.date < b.date ? 1 : -1));

const js =
  "// Auto-generated by build.js. Do not edit manually.\n" +
  "window.POSTS = " +
  JSON.stringify(posts, null, 2) +
  ";\n";

fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
fs.writeFileSync(OUT_FILE, js, "utf8");
console.log("Generated " + OUT_FILE + " with " + posts.length + " posts.");
